### ISSUE TITLE
deb: Simplify package scripts

### ISSUE THREAD

**Issue by ashie** [fluent-plugins-nursery/td-agent-builder#13]
We have package scripts for Debian that are comes from omnibus-td-agent:

* https://github.com/treasure-data/omnibus-td-agent/tree/master/templates/package-scripts/td-agent/deb
* https://github.com/clear-code/td-agent-builder/tree/master/td-agent/templates/package-scripts/td-agent/deb

Some of them aren't needed in the new build system since they are for avoiding Omibius's limitations (maybe). I want to remove needless codes and keep it simple.

**Comment by ashie** [comment]
For RPM we removed package scripts since they doesn't seem needed anymore for the new build system.

**Comment by kenhys** [comment]
* Remove duplicated copyright.

**Comment by kenhys** [comment]
>     * Remove duplicated copyright.

It should be removed by https://github.com/fluent-plugins-nursery/td-agent-builder/pull/137

**Comment by kenhys** [comment]
* Drop needless prerm

**Comment by kenhys** [comment]
>     * Drop needless prerm

It should be fixed by https://github.com/fluent-plugins-nursery/td-agent-builder/pull/138

**Comment by kenhys** [comment]
I've fixed not synced copyright file about ruby version.
https://github.com/fluent-plugins-nursery/td-agent-builder/pull/139

**Comment by kenhys** [comment]
Oops.

```
Building native extensions. This could take a while...                                                                                                       
ERROR:  Error installing /build/td-agent-4.0.0/td-agent/downloads/plugin_gems/16-rdkafka-0.8.0.gem:
        ERROR: Failed to build gem native extension.                                                                                                         
                                                                                                                                                             
    current directory: /build/td-agent-4.0.0/debian/tmp/opt/td-agent/lib/ruby/gems/2.7.0/gems/rdkafka-0.8.0/ext
/opt/td-agent/bin/ruby -I/opt/td-agent/lib/ruby/2.7.0/rubygems -rrubygems /opt/td-agent/lib/ruby/gems/2.7.0/gems/rake-13.0.1/exe/rake RUBYARCHDIR\=/build/td-
agent-4.0.0/debian/tmp/opt/td-agent/lib/ruby/gems/2.7.0/extensions/x86_64-linux/2.7.0/rdkafka-0.8.0 RUBYLIBDIR\=/build/td-agent-4.0.0/debian/tmp/opt/td-agent
/lib/ruby/gems/2.7.0/extensions/x86_64-linux/2.7.0/rdkafka-0.8.0
rake aborted!
OpenURI::HTTPError: 500 Internal Server Error
/build/td-agent-4.0.0/debian/tmp/opt/td-agent/lib/ruby/gems/2.7.0/gems/rdkafka-0.8.0/ext/Rakefile:14:in `block in download_file_http'
/build/td-agent-4.0.0/debian/tmp/opt/td-agent/lib/ruby/gems/2.7.0/gems/mini_portile2-2.5.0/lib/mini_portile2/mini_portile.rb:543:in `with_tempfile'
/build/td-agent-4.0.0/debian/tmp/opt/td-agent/lib/ruby/gems/2.7.0/gems/rdkafka-0.8.0/ext/Rakefile:12:in `download_file_http'
/build/td-agent-4.0.0/debian/tmp/opt/td-agent/lib/ruby/gems/2.7.0/gems/mini_portile2-2.5.0/lib/mini_portile2/mini_portile.rb:440:in `download_file'
/build/td-agent-4.0.0/debian/tmp/opt/td-agent/lib/ruby/gems/2.7.0/gems/mini_portile2-2.5.0/lib/mini_portile2/mini_portile.rb:54:in `block in download'
/build/td-agent-4.0.0/debian/tmp/opt/td-agent/lib/ruby/gems/2.7.0/gems/mini_portile2-2.5.0/lib/mini_portile2/mini_portile.rb:53:in `each'
/build/td-agent-4.0.0/debian/tmp/opt/td-agent/lib/ruby/gems/2.7.0/gems/mini_portile2-2.5.0/lib/mini_portile2/mini_portile.rb:53:in `download'
/build/td-agent-4.0.0/debian/tmp/opt/td-agent/lib/ruby/gems/2.7.0/gems/mini_portile2-2.5.0/lib/mini_portile2/mini_portile.rb:150:in `cook'
/build/td-agent-4.0.0/debian/tmp/opt/td-agent/lib/ruby/gems/2.7.0/gems/rdkafka-0.8.0/ext/Rakefile:37:in `block in <top (required)>'
Tasks: TOP => default
(See full trace by running task with --trace)

```

**Comment by kenhys** [comment]
I'll close if https://github.com/fluent-plugins-nursery/td-agent-builder/pull/140 is changed from draft PR, and reviewed and merged.

**Comment by kenhys** [comment]
#140 was merged into master.
